name: Django CI & Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # 3️⃣ Install dependencies
      - name: Install dependencies
        working-directory: myproject
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install  -r requirements.txt; fi

      # 4️⃣ Run migrations
      - name: Run migrations
        working-directory: myproject
        env:
          DJANGO_SETTINGS_MODULE: myproject.settings_test
        run: |
          python manage.py makemigrations --settings=myproject.settings_test
          python manage.py migrate --noinput --settings=myproject.settings_test

      # 5️⃣ Run Django tests
      - name: Run Django Tests
        working-directory: myproject
        env:
          DJANGO_SETTINGS_MODULE: myproject.settings_test
        run: |
          python manage.py test cours --settings=myproject.settings_test --verbosity=2

      # 6️⃣ Verify Dockerfile location
      - name: Verify Dockerfile
        run: |
          echo "Listing files in myproject/"
          ls -l myproject/

      # 7️⃣ Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 8️⃣ Build Docker Image (Dockerfile موجود في myproject/)
      - name: Build Docker Image
        working-directory: myproject
        run: |
          docker build -f Dockerfile -t django-app .

      # 9️⃣ Deploy to Render
      - name: Deploy to Render
        run: |
          curl -X POST "https://api.render.com/deploy/srv-d4k83sbuibrs73fatdt0?key=rnd_q3BUcT9zhiOIuzP0YlaPgXUnyZqJ"
